name: CI
on:
  push:
    branches:
      - main
      - beta
      - next
      - dev*
    paths-ignore:
      - "*.md"
      - "docs/**"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - "*.md"
      - "docs/**"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["18", "20", "22"]
        eleventy: ["1", "2"]
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }} against @11ty/eleventy@${{ matrix.eleventy }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # cache: npm
      - run: npm install
      - run: npm install @11ty/eleventy@${{ matrix.eleventy }}
      - run: npm test
env:
  YARN_GPG: no
